In [82]:
%pip install --upgrade plotly pandas

Requirement already satisfied: plotly in ./.venv-1/lib/python3.13/site-packages (7.1.0)
Requirement already satisfied: pandas in ./.venv-1/lib/python3.13/site-packages (3.0.6)
Requirement already satisfied: narwhals>=1.15.1 in ./.venv-1/lib/python3.13/site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in ./.venv-1/lib/python3.13/site-packages (from plotly) (26.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv-1/lib/python3.13/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv-1/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv-1/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [83]:
import pandas as pd 
import numpy as np
import datetime as dt 
import yfinance as yf 
import seaborn as sns 
import plotly.express as px
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import random as rd
import plotly.graph_objects as go

In [84]:
raw_df = pd.read_csv('Diversified_stocks.csv')
raw_df

,Date,Tata Elxsi,HDFC,Sun Pharma,LT,NTPC,HAL,Titan,Airtel,Maruti
0,2021-01-01,1751.431,663.906,561.122,1218.873,79.22,388.796,1529.710,488.066,7298.333
1,2021-01-04,1763.760,659.689,568.792,1235.413,79.22,402.455,1522.153,489.913,7308.772
2,2021-01-05,1835.770,664.674,567.898,1227.613,78.06,418.178,1541.831,486.976,7264.316
3,2021-01-06,1870.180,661.809,569.639,1234.849,78.26,428.274,1543.451,497.682,7238.838
4,2021-01-07,1874.259,659.806,566.439,1258.296,77.58,422.239,1513.761,516.583,7179.483
...,...,...,...,...,...,...,...,...,...,...
1412,2026-09-14,3383.000,708.250,1840.000,3930.700,333.40,4905.000,5009.500,1831.100,12400.000
1413,2026-09-15,3440.000,716.550,1835.000,3850.700,329.50,4695.000,4856.000,1830.400,12231.000
1414,2026-09-16,3373.000,721.500,1853.500,3807.700,327.00,4695.600,4908.500,1835.000,12166.000
1415,2026-09-17,3381.800,713.000,1867.300,3836.200,329.60,4788.000,4841.000,1836.000,12338.000
1416,2026-09-18,3266.700,731.000,1837.300,3885.000,323.65,4800.300,4798.500,1893.300,12103.000

In [85]:
portfolio_df = raw_df.copy()
scaled_df = price_scaling(portfolio_df)
scaled_df

,Date,Tata Elxsi,HDFC,Sun Pharma,LT,NTPC,HAL,Titan,Airtel,Maruti
0,2021-01-01,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,2021-01-04,1.007039,0.993648,1.013669,1.013570,1.000000,1.035132,0.995060,1.003784,1.001430
2,2021-01-05,1.048154,1.001157,1.012076,1.007171,0.985357,1.075572,1.007924,0.997767,0.995339
3,2021-01-06,1.067801,0.996841,1.015179,1.013107,0.987882,1.101539,1.008983,1.019702,0.991848
4,2021-01-07,1.070130,0.993824,1.009476,1.032344,0.979298,1.086017,0.989574,1.058429,0.983715
...,...,...,...,...,...,...,...,...,...,...
1412,2026-09-14,1.931563,1.066793,3.279144,3.224864,4.208533,12.615871,3.274804,3.751747,1.699018
1413,2026-09-15,1.964108,1.079294,3.270234,3.159230,4.159303,12.075742,3.174458,3.750312,1.675862
1414,2026-09-16,1.925854,1.086750,3.303203,3.123951,4.127746,12.077285,3.208778,3.759737,1.666956
1415,2026-09-17,1.930878,1.073947,3.327797,3.147334,4.160566,12.314942,3.164652,3.761786,1.690523
1416,2026-09-18,1.865161,1.101059,3.274332,3.187371,4.085458,12.346578,3.136869,3.879188,1.658324

In [86]:
def price_scaling(raw_prices_df):
    scaled_prices_df = raw_prices_df.copy()
    for i in raw_prices_df.columns[1:]:
          scaled_prices_df[i] = raw_prices_df[i]/raw_prices_df[i][0]
    return scaled_prices_df

In [87]:
scaled_df = price_scaling(raw_df)
scaled_df

,Date,Tata Elxsi,HDFC,Sun Pharma,LT,NTPC,HAL,Titan,Airtel,Maruti
0,2021-01-01,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,2021-01-04,1.007039,0.993648,1.013669,1.013570,1.000000,1.035132,0.995060,1.003784,1.001430
2,2021-01-05,1.048154,1.001157,1.012076,1.007171,0.985357,1.075572,1.007924,0.997767,0.995339
3,2021-01-06,1.067801,0.996841,1.015179,1.013107,0.987882,1.101539,1.008983,1.019702,0.991848
4,2021-01-07,1.070130,0.993824,1.009476,1.032344,0.979298,1.086017,0.989574,1.058429,0.983715
...,...,...,...,...,...,...,...,...,...,...
1412,2026-09-14,1.931563,1.066793,3.279144,3.224864,4.208533,12.615871,3.274804,3.751747,1.699018
1413,2026-09-15,1.964108,1.079294,3.270234,3.159230,4.159303,12.075742,3.174458,3.750312,1.675862
1414,2026-09-16,1.925854,1.086750,3.303203,3.123951,4.127746,12.077285,3.208778,3.759737,1.666956
1415,2026-09-17,1.930878,1.073947,3.327797,3.147334,4.160566,12.314942,3.164652,3.761786,1.690523
1416,2026-09-18,1.865161,1.101059,3.274332,3.187371,4.085458,12.346578,3.136869,3.879188,1.658324

In [88]:
weights = [0.032266, 0.094461, 0.117917, 0.132624, 0.145942, 0.128299, 0.10009, 0.007403, 0.088581, 0.152417]
weights

[0.032266,
 0.094461,
 0.117917,
 0.132624,
 0.145942,
 0.128299,
 0.10009,
 0.007403,
 0.088581,
 0.152417]

In [89]:

def generate_portfolio_weights(n):
    weights = []
    for i in range(n):
        weights.append(rd.random())
        
    weights = weights/np.sum(weights)
    return weights

In [90]:
weights = generate_portfolio_weights(6)
print(weights)

[0.07495886 0.03724818 0.24743493 0.26412189 0.08882096 0.28741518]

In [91]:
def asset_allocation(df, weights, initial_investment):
    portfolio_df = df.copy()
    scaled_df = price_scaling(df)
  
    for i, stock in enumerate(scaled_df.columns[1:]):
        portfolio_df[stock] = scaled_df[stock] * weights[i] * initial_investment
    portfolio_df['Portfolio Value [INR]'] = portfolio_df[portfolio_df != 'Date'].sum(axis = 1, numeric_only = True)
    portfolio_df['Portfolio Daily Return [%]'] = portfolio_df['Portfolio Value [INR]'].pct_change(1) * 100 
    portfolio_df.replace(np.nan, 0, inplace = True)
    
    return portfolio_df

In [92]:
n = len(raw_df.columns)-1

print('Number of stocks in the portfolio = {}'.format(n))
weights = generate_portfolio_weights(n).round(6)
print('Portfolio weights in order = {}'.format(weights))
portfolio_df = asset_allocation(raw_df, weights, 1000000)
portfolio_df.round(1)

Number of stocks in the portfolio = 9
Portfolio weights in order = [0.13721  0.142512 0.092397 0.080761 0.152854 0.005906 0.140269 0.154496
 0.093596]

,Date,Tata Elxsi,HDFC,Sun Pharma,LT,NTPC,HAL,Titan,Airtel,Maruti,Portfolio Value [INR],Portfolio Daily Return [%]
0,2021-01-01,137210.0,142512.0,92397.0,80761.0,152854.0,5906.0,140269.0,154496.0,93596.0,1000001.0,0.0
1,2021-01-04,138175.9,141606.8,93660.0,81856.9,152854.0,6113.5,139576.0,155080.7,93729.9,1002653.6,0.3
2,2021-01-05,143817.3,142676.9,93512.8,81340.1,150615.8,6352.3,141380.5,154151.0,93159.8,1007006.3,0.4
3,2021-01-06,146513.0,142061.9,93799.4,81819.5,151001.7,6505.7,141529.0,157539.9,92833.0,1013603.2,0.7
4,2021-01-07,146832.5,141631.9,93272.5,83373.1,149689.6,6414.0,138806.5,163523.0,92071.8,1015615.1,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...
1412,2026-09-14,265029.8,152030.7,302983.1,260443.3,643291.1,74509.3,459353.4,579629.9,159021.3,2896292.0,0.0
1413,2026-09-15,269495.3,153812.4,302159.8,255142.6,635766.1,71319.3,445278.0,579408.3,156854.0,2869235.8,-0.9
1414,2026-09-16,264246.4,154874.9,305206.1,252293.4,630942.4,71328.4,450092.1,580864.4,156020.4,2865868.6,-0.1
1415,2026-09-17,264935.8,153050.4,307478.4,254181.8,635959.1,72732.0,443902.6,581180.9,158226.2,2871647.3,0.2
1416,2026-09-18,255918.7,156914.2,302538.5,257415.2,624478.6,72918.9,440005.5,599319.1,155212.5,2864721.2,-0.2

In [93]:
%pip uninstall plotly -y
%pip install plotly --no-cache-dir

Found existing installation: plotly 7.1.0
Uninstalling plotly-7.1.0:
  Successfully uninstalled plotly-7.1.0
Note: you may need to restart the kernel to use updated packages.
Collecting plotly
  Downloading plotly-7.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: narwhals>=1.15.1 in ./.venv-1/lib/python3.13/site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in ./.venv-1/lib/python3.13/site-packages (from plotly) (26.3)
Downloading plotly-7.1.0-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 6.5 MB/s  0:00:01 eta 0:00:01m
Installing collected packages: plotly
Successfully installed plotly-7.1.0

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [94]:
import plotly

import plotly.express as px

In [95]:
def plot_financial_data(df, title):
    
    fig = px.line(title = title)
    
    # For loop that plots all stock prices in the pandas dataframe df
    # Note that index starts with 1 because we want to skip the date column
    
    for i in df.columns[1:]:
        fig.add_scatter(x = df['Date'], y = df[i], name = i)

    fig.show()

In [96]:
portfolio_df

,Date,Tata Elxsi,HDFC,Sun Pharma,LT,NTPC,HAL,Titan,Airtel,Maruti,Portfolio Value [INR],Portfolio Daily Return [%]
0,2021-01-01,137210.000000,142512.000000,92397.000000,80761.000000,152854.000000,5906.000000,140269.000000,154496.000000,93596.000000,1.000001e+06,0.000000
1,2021-01-04,138175.874242,141606.791877,93659.978443,81856.919706,152854.000000,6113.486841,139576.049811,155080.662960,93729.872851,1.002654e+06,0.265263
2,2021-01-05,143817.256689,142676.856495,93512.768179,81340.101465,150615.794496,6352.326845,141380.452856,154150.963386,93159.755842,1.007006e+06,0.434112
3,2021-01-06,146512.992975,142061.864493,93799.449466,81819.549772,151001.691997,6505.689987,141529.001130,157539.919339,92833.018368,1.013603e+06,0.655100
4,2021-01-07,146832.548579,141631.906734,93272.522345,83373.118656,149689.640495,6414.015407,138806.533074,163522.980843,92071.832139,1.015615e+06,0.198492
...,...,...,...,...,...,...,...,...,...,...,...,...
1412,2026-09-14,265029.812765,152030.745316,302983.094585,260443.264146,643291.133552,74509.331372,459353.443136,579629.856618,159021.299795,2.896292e+06,0.000000
1413,2026-09-15,269495.286997,153812.397538,302159.770959,255142.564238,635766.132290,71319.329417,445278.035706,579408.273471,156853.993371,2.869236e+06,-0.934167
1414,2026-09-16,264246.396233,154874.949164,305206.068377,252293.438037,630942.413532,71328.443708,450092.100137,580864.391291,156020.413977,2.865869e+06,-0.117354
1415,2026-09-17,264935.802781,153050.365564,307478.441587,254181.812379,635959.081040,72732.044568,443902.588726,581180.938644,158226.193296,2.871647e+06,0.201637
1416,2026-09-18,255918.678498,156914.189659,302538.499827,257415.239324,624478.630396,72918.887540,440005.488949,599319.101925,155212.483179,2.864721e+06,-0.241188

In [102]:
plot_financial_data(portfolio_df[['Date', 'Portfolio Daily Return [%]']], 'Portfolio Percentage Daily Return [%]')

plot_financial_data(portfolio_df.drop(['Portfolio Value [INR]', 'Portfolio Daily Return [%]'], axis = 1), 'Portfolio positions [$]')

plot_financial_data(portfolio_df[['Date', 'Portfolio Value [INR]']], 'Total Portfolio Value [$]')

In [117]:
def simulation_engine(weights, initial_investment):
    
    portfolio_df = asset_allocation(
        raw_df,
        weights,
        initial_investment
    )
    
    return_on_investment = (
        (portfolio_df['Portfolio Value [INR]'].iloc[-1] -
         portfolio_df['Portfolio Value [INR]'].iloc[0])
        / portfolio_df['Portfolio Value [INR]'].iloc[0]
    ) * 100
    
    # Remove non-stock columns
    portfolio_daily_return_df = portfolio_df.drop(
        columns=[
            'Date',
            'Portfolio Value [INR]',
            'Portfolio Daily Return [%]'
        ]
    )
    
    # Calculate daily returns of individual stocks
    portfolio_daily_return_df = portfolio_daily_return_df.pct_change(1)
    
    # Expected annual portfolio return
    expected_portfolio_return = (
        np.sum(
            weights * portfolio_daily_return_df.mean()
        ) * 252
    )
    
    # Annualized covariance matrix
    covariance = portfolio_daily_return_df.cov() * 252
    
    # Portfolio volatility
    expected_volatility = np.sqrt(
        np.dot(
            weights.T,
            np.dot(covariance, weights)
        )
    )
    
    # Risk-free rate assumption
    rf = 0.07
    
    # Sharpe ratio
    sharpe_ratio = (
        expected_portfolio_return - rf
    ) / expected_volatility
    
    return (
        expected_portfolio_return,
        expected_volatility,
        sharpe_ratio,
        portfolio_df['Portfolio Value [INR]'].iloc[-1],
        return_on_investment
    )

In [118]:
initial_investment = 1000000
portfolio_metrics = simulation_engine(weights, initial_investment)

In [119]:
print('Expected Portfolio Annual Return = {:.2f}%'.format(portfolio_metrics[0] * 100))
print('Portfolio Standard Deviation (Volatility) = {:.2f}%'.format(portfolio_metrics[1] * 100))
print('Sharpe Ratio = {:.2f}'.format(portfolio_metrics[2]))
print('Portfolio Final Value = ${:.2f}'.format(portfolio_metrics[3]))
print('Return on Investment = {:.2f}%'.format(portfolio_metrics[4]))

Expected Portfolio Annual Return = 24.76%
Portfolio Standard Deviation (Volatility) = 15.90%
Sharpe Ratio = 1.12
Portfolio Final Value = $4324642.08
Return on Investment = 332.46%

In [120]:
#MONTE CARLO SIMULATION function for 5000 runs
sim_runs = 5000
initial_investment = 1000000

# Placeholder to store all weights
weights_runs = np.zeros((sim_runs, n))

# Placeholder to store all Sharpe ratios
sharpe_ratio_runs = np.zeros(sim_runs)

# Placeholder to store all expected returns
expected_portfolio_returns_runs = np.zeros(sim_runs)

# Placeholder to store all volatility values
volatility_runs = np.zeros(sim_runs)

# Placeholder to store all returns on investment
return_on_investment_runs = np.zeros(sim_runs)

# Placeholder to store all final portfolio values
final_value_runs = np.zeros(sim_runs)

for i in range(sim_runs):
    # Generate random weights 
    weights = generate_portfolio_weights(n)
    # Store the weights
    weights_runs[i,:] = weights
    
    # Call "simulation_engine" function and store Sharpe ratio, return and volatility
    # Note that asset allocation is performed using the "asset_allocation" function  
    expected_portfolio_returns_runs[i], volatility_runs[i], sharpe_ratio_runs[i], final_value_runs[i], return_on_investment_runs[i] = simulation_engine(weights, initial_investment)
    print("Simulation Run = {}".format(i))   
    print("Weights = {}, Final Value = ${:.2f}, Sharpe Ratio = {:.2f}".format(weights_runs[i].round(3), final_value_runs[i], sharpe_ratio_runs[i]))   
    print('\n')

Simulation Run = 0
Weights = [0.079 0.167 0.196 0.029 0.223 0.143 0.125 0.018 0.019], Final Value = $4239553.76, Sharpe Ratio = 1.14


Simulation Run = 1
Weights = [0.141 0.058 0.149 0.123 0.111 0.07  0.114 0.147 0.088], Final Value = $3591966.42, Sharpe Ratio = 1.09


Simulation Run = 2
Weights = [0.108 0.194 0.033 0.114 0.186 0.031 0.135 0.077 0.122], Final Value = $2953709.94, Sharpe Ratio = 0.83


Simulation Run = 3
Weights = [0.104 0.082 0.177 0.06  0.182 0.044 0.138 0.032 0.18 ], Final Value = $3200172.93, Sharpe Ratio = 0.96


Simulation Run = 4
Weights = [0.076 0.073 0.023 0.072 0.105 0.187 0.124 0.158 0.182], Final Value = $4566423.25, Sharpe Ratio = 1.17


Simulation Run = 5
Weights = [0.182 0.111 0.108 0.056 0.111 0.123 0.015 0.191 0.103], Final Value = $3929241.72, Sharpe Ratio = 1.07


Simulation Run = 6
Weights = [0.151 0.146 0.023 0.09  0.093 0.182 0.157 0.061 0.096], Final Value = $4319207.47, Sharpe Ratio = 1.05


Simulation Run = 7
Weights = [0.157 0.135 0.098 0.075 0.162 0.045 0.015 0.141 0.172], Final Value = $3096753.44, Sharpe Ratio = 0.89


Simulation Run = 8
Weights = [0.149 0.161 0.082 0.045 0.012 0.082 0.193 0.076 0.199], Final Value = $3159829.90, Sharpe Ratio = 0.82


Simulation Run = 9
Weights = [0.198 0.181 0.139 0.019 0.105 0.107 0.038 0.093 0.12 ], Final Value = $3513586.69, Sharpe Ratio = 0.92


Simulation Run = 10
Weights = [0.091 0.002 0.022 0.17  0.056 0.144 0.205 0.192 0.118], Final Value = $4379677.03, Sharpe Ratio = 1.19


Simulation Run = 11
Weights = [0.168 0.086 0.1   0.106 0.126 0.184 0.13  0.036 0.064], Final Value = $4515546.48, Sharpe Ratio = 1.14


Simulation Run = 12
Weights = [0.087 0.107 0.121 0.139 0.128 0.096 0.101 0.075 0.146], Final Value = $3675992.17, Sharpe Ratio = 1.04


Simulation Run = 13
Weights = [0.071 0.058 0.174 0.063 0.073 0.101 0.125 0.192 0.144], Final Value = $3880857.16, Sharpe Ratio = 1.16


Simulation Run = 14
Weights = [0.06  0.022 0.241 0.055 0.005 0.274 0.156 0.012 0.175], Final Value = $5327385.86, Sharpe Ratio = 1.27


Simulation Run = 15
Weights = [0.149 0.074 0.096 0.117 0.164 0.048 0.033 0.173 0.145], Final Value = $3330373.05, Sharpe Ratio = 1.00


Simulation Run = 16
Weights = [0.157 0.153 0.088 0.138 0.147 0.113 0.041 0.106 0.056], Final Value = $3823980.11, Sharpe Ratio = 1.02


Simulation Run = 17
Weights = [0.21  0.023 0.106 0.015 0.042 0.061 0.208 0.227 0.109], Final Value = $3450282.64, Sharpe Ratio = 1.02


Simulation Run = 18
Weights = [0.091 0.095 0.112 0.109 0.045 0.187 0.086 0.189 0.087], Final Value = $4628329.76, Sharpe Ratio = 1.22


Simulation Run = 19
Weights = [0.21  0.047 0.059 0.114 0.146 0.003 0.217 0.141 0.064], Final Value = $2962274.74, Sharpe Ratio = 0.92


Simulation Run = 20
Weights = [0.129 0.145 0.002 0.168 0.11  0.148 0.019 0.109 0.169], Final Value = $3982059.94, Sharpe Ratio = 0.97


Simulation Run = 21
Weights = [0.194 0.146 0.158 0.006 0.045 0.08  0.062 0.145 0.164], Final Value = $3263326.04, Sharpe Ratio = 0.89


Simulation Run = 22
Weights = [0.137 0.034 0.171 0.08  0.092 0.151 0.14  0.146 0.049], Final Value = $4429340.09, Sharpe Ratio = 1.26


Simulation Run = 23
Weights = [0.116 0.002 0.16  0.152 0.012 0.218 0.207 0.12  0.014], Final Value = $5099909.33, Sharpe Ratio = 1.32


Simulation Run = 24
Weights = [0.255 0.096 0.049 0.007 0.14  0.07  0.13  0.053 0.2  ], Final Value = $3144872.08, Sharpe Ratio = 0.81


Simulation Run = 25
Weights = [0.036 0.178 0.063 0.061 0.179 0.173 0.214 0.062 0.033], Final Value = $4498404.31, Sharpe Ratio = 1.14


Simulation Run = 26
Weights = [0.19  0.185 0.127 0.09  0.042 0.115 0.083 0.043 0.124], Final Value = $3488864.59, Sharpe Ratio = 0.88


Simulation Run = 27
Weights = [0.089 0.046 0.051 0.067 0.18  0.132 0.145 0.176 0.113], Final Value = $4291189.82, Sharpe Ratio = 1.21


Simulation Run = 28
Weights = [0.281 0.286 0.021 0.025 0.152 0.091 0.035 0.037 0.072], Final Value = $3100615.75, Sharpe Ratio = 0.67


Simulation Run = 29
Weights = [0.183 0.088 0.099 0.079 0.089 0.081 0.113 0.111 0.156], Final Value = $3422770.78, Sharpe Ratio = 0.96


Simulation Run = 30
Weights = [0.006 0.169 0.025 0.228 0.041 0.209 0.074 0.067 0.18 ], Final Value = $4552826.72, Sharpe Ratio = 1.02


Simulation Run = 31
Weights = [0.191 0.037 0.118 0.029 0.149 0.116 0.067 0.205 0.089], Final Value = $4062844.81, Sharpe Ratio = 1.16


Simulation Run = 32
Weights = [0.098 0.164 0.119 0.12  0.104 0.051 0.054 0.129 0.16 ], Final Value = $3127753.17, Sharpe Ratio = 0.90


Simulation Run = 33
Weights = [0.158 0.026 0.108 0.114 0.096 0.119 0.1   0.147 0.132], Final Value = $4007717.64, Sharpe Ratio = 1.14


Simulation Run = 34
Weights = [0.086 0.098 0.213 0.043 0.214 0.198 0.096 0.032 0.019], Final Value = $4885907.70, Sharpe Ratio = 1.27


Simulation Run = 35
Weights = [0.089 0.149 0.078 0.011 0.108 0.133 0.165 0.137 0.13 ], Final Value = $3965705.90, Sharpe Ratio = 1.07


Simulation Run = 36
Weights = [0.024 0.069 0.026 0.171 0.283 0.075 0.001 0.274 0.078], Final Value = $4023106.87, Sharpe Ratio = 1.14


Simulation Run = 37
Weights = [0.07  0.135 0.108 0.005 0.049 0.157 0.138 0.156 0.183], Final Value = $4126857.39, Sharpe Ratio = 1.09


Simulation Run = 38
Weights = [0.136 0.046 0.107 0.162 0.145 0.038 0.044 0.209 0.111], Final Value = $3374115.12, Sharpe Ratio = 1.05


Simulation Run = 39
Weights = [0.17  0.116 0.03  0.098 0.195 0.137 0.052 0.115 0.087], Final Value = $4098277.75, Sharpe Ratio = 1.06


Simulation Run = 40
Weights = [0.09  0.139 0.071 0.137 0.199 0.072 0.131 0.111 0.05 ], Final Value = $3616339.07, Sharpe Ratio = 1.04


Simulation Run = 41
Weights = [0.105 0.162 0.001 0.121 0.072 0.184 0.061 0.108 0.186], Final Value = $4245775.89, Sharpe Ratio = 1.00


Simulation Run = 42
Weights = [0.156 0.116 0.108 0.055 0.168 0.045 0.086 0.117 0.149], Final Value = $3161649.58, Sharpe Ratio = 0.93


Simulation Run = 43
Weights = [0.051 0.041 0.203 0.061 0.23  0.038 0.252 0.065 0.061], Final Value = $3541930.50, Sharpe Ratio = 1.12


Simulation Run = 44
Weights = [0.163 0.181 0.083 0.029 0.066 0.004 0.162 0.142 0.169], Final Value = $2533382.37, Sharpe Ratio = 0.73


Simulation Run = 45
Weights = [0.07  0.121 0.004 0.06  0.167 0.163 0.12  0.132 0.163], Final Value = $4319556.39, Sharpe Ratio = 1.10


Simulation Run = 46
Weights = [0.189 0.112 0.105 0.201 0.033 0.077 0.024 0.129 0.13 ], Final Value = $3337834.78, Sharpe Ratio = 0.90


Simulation Run = 47
Weights = [0.019 0.207 0.165 0.093 0.103 0.014 0.208 0.145 0.047], Final Value = $2980526.18, Sharpe Ratio = 0.91


Simulation Run = 48
Weights = [0.008 0.023 0.115 0.122 0.159 0.105 0.143 0.09  0.235], Final Value = $3939238.74, Sharpe Ratio = 1.11


Simulation Run = 49
Weights = [0.176 0.022 0.065 0.043 0.186 0.144 0.058 0.179 0.127], Final Value = $4329645.09, Sharpe Ratio = 1.17


Simulation Run = 50
Weights = [0.112 0.187 0.004 0.147 0.013 0.163 0.183 0.068 0.123], Final Value = $4000383.39, Sharpe Ratio = 0.94


Simulation Run = 51
Weights = [0.004 0.173 0.17  0.14  0.063 0.127 0.159 0.055 0.109], Final Value = $3916267.18, Sharpe Ratio = 1.05


Simulation Run = 52
Weights = [0.12  0.019 0.224 0.173 0.094 0.144 0.095 0.091 0.041], Final Value = $4410135.46, Sharpe Ratio = 1.25


Simulation Run = 53
Weights = [0.154 0.249 0.013 0.04  0.14  0.016 0.001 0.143 0.244], Final Value = $2461098.25, Sharpe Ratio = 0.61


Simulation Run = 54
Weights = [0.161 0.193 0.15  0.033 0.177 0.107 0.134 0.031 0.014], Final Value = $3716795.32, Sharpe Ratio = 1.00


Simulation Run = 55
Weights = [0.174 0.172 0.178 0.021 0.028 0.095 0.133 0.102 0.097], Final Value = $3420725.49, Sharpe Ratio = 0.93


Simulation Run = 56
Weights = [0.181 0.049 0.12  0.082 0.108 0.15  0.163 0.091 0.055], Final Value = $4298892.96, Sharpe Ratio = 1.16


Simulation Run = 57
Weights = [0.108 0.1   0.151 0.138 0.188 0.002 0.192 0.026 0.095], Final Value = $2901707.73, Sharpe Ratio = 0.91


Simulation Run = 58
Weights = [0.219 0.066 0.084 0.174 0.21  0.026 0.038 0.154 0.029], Final Value = $3255153.16, Sharpe Ratio = 0.97


Simulation Run = 59
Weights = [0.168 0.073 0.129 0.18  0.042 0.019 0.158 0.103 0.127], Final Value = $2906468.38, Sharpe Ratio = 0.88


Simulation Run = 60
Weights = [0.01  0.109 0.13  0.121 0.166 0.102 0.146 0.117 0.099], Final Value = $3959786.47, Sharpe Ratio = 1.14


Simulation Run = 61
Weights = [0.132 0.049 0.039 0.119 0.135 0.109 0.13  0.154 0.134], Final Value = $3924100.87, Sharpe Ratio = 1.10


Simulation Run = 62
Weights = [0.089 0.149 0.014 0.128 0.224 0.191 0.137 0.007 0.06 ], Final Value = $4613758.36, Sharpe Ratio = 1.10


Simulation Run = 63
Weights = [0.045 0.197 0.038 0.124 0.055 0.073 0.184 0.151 0.134], Final Value = $3327765.95, Sharpe Ratio = 0.90


Simulation Run = 64
Weights = [0.126 0.139 0.151 0.009 0.136 0.078 0.146 0.065 0.151], Final Value = $3384834.69, Sharpe Ratio = 0.97


Simulation Run = 65
Weights = [0.093 0.098 0.108 0.159 0.157 0.178 0.017 0.172 0.017], Final Value = $4735761.25, Sharpe Ratio = 1.24


Simulation Run = 66
Weights = [0.103 0.126 0.056 0.076 0.166 0.146 0.081 0.097 0.149], Final Value = $4118933.29, Sharpe Ratio = 1.08


Simulation Run = 67
Weights = [0.181 0.06  0.023 0.164 0.165 0.004 0.073 0.162 0.169], Final Value = $2859508.14, Sharpe Ratio = 0.86


Simulation Run = 68
Weights = [0.169 0.15  0.189 0.118 0.029 0.15  0.009 0.115 0.072], Final Value = $4034895.47, Sharpe Ratio = 1.04


Simulation Run = 69
Weights = [0.098 0.208 0.187 0.076 0.034 0.205 0.049 0.134 0.009], Final Value = $4624477.18, Sharpe Ratio = 1.15


Simulation Run = 70
Weights = [0.005 0.227 0.101 0.122 0.104 0.086 0.109 0.192 0.055], Final Value = $3642633.58, Sharpe Ratio = 1.00


Simulation Run = 71
Weights = [0.108 0.122 0.218 0.134 0.109 0.037 0.167 0.002 0.105], Final Value = $3078193.67, Sharpe Ratio = 0.92


Simulation Run = 72
Weights = [0.082 0.014 0.106 0.019 0.321 0.096 0.003 0.34  0.019], Final Value = $4434108.88, Sharpe Ratio = 1.27


Simulation Run = 73
Weights = [0.017 0.12  0.045 0.171 0.237 0.112 0.124 0.057 0.116], Final Value = $4015294.98, Sharpe Ratio = 1.07


Simulation Run = 74
Weights = [0.094 0.143 0.152 0.091 0.168 0.    0.112 0.178 0.062], Final Value = $2955550.64, Sharpe Ratio = 0.96


Simulation Run = 75
Weights = [0.181 0.017 0.054 0.092 0.149 0.236 0.044 0.051 0.176], Final Value = $4980047.87, Sharpe Ratio = 1.16


Simulation Run = 76
Weights = [0.082 0.019 0.135 0.205 0.201 0.206 0.136 0.011 0.005], Final Value = $5112241.55, Sharpe Ratio = 1.29


Simulation Run = 77
Weights = [0.235 0.1   0.159 0.056 0.035 0.019 0.211 0.016 0.169], Final Value = $2624595.15, Sharpe Ratio = 0.73


Simulation Run = 78
Weights = [0.166 0.109 0.129 0.167 0.016 0.164 0.021 0.055 0.173], Final Value = $4045559.10, Sharpe Ratio = 0.99


Simulation Run = 79
Weights = [0.089 0.137 0.149 0.076 0.217 0.076 0.118 0.136 0.003], Final Value = $3767766.66, Sharpe Ratio = 1.12


Simulation Run = 80
Weights = [0.101 0.158 0.19  0.06  0.057 0.176 0.137 0.084 0.037], Final Value = $4399208.09, Sharpe Ratio = 1.16


Simulation Run = 81
Weights = [0.039 0.01  0.175 0.087 0.195 0.226 0.016 0.005 0.247], Final Value = $5003246.23, Sharpe Ratio = 1.21


Simulation Run = 82
Weights = [0.077 0.079 0.203 0.024 0.182 0.145 0.176 0.033 0.081], Final Value = $4320940.06, Sharpe Ratio = 1.21


Simulation Run = 83
Weights = [0.072 0.004 0.127 0.138 0.022 0.131 0.17  0.166 0.169], Final Value = $4164069.06, Sharpe Ratio = 1.18


Simulation Run = 84
Weights = [0.097 0.077 0.084 0.123 0.17  0.065 0.098 0.204 0.081], Final Value = $3669897.87, Sharpe Ratio = 1.11


Simulation Run = 85
Weights = [0.187 0.12  0.106 0.016 0.127 0.144 0.147 0.049 0.105], Final Value = $3995215.06, Sharpe Ratio = 1.04


Simulation Run = 86
Weights = [0.17  0.045 0.113 0.123 0.097 0.201 0.008 0.039 0.205], Final Value = $4517065.49, Sharpe Ratio = 1.09


Simulation Run = 87
Weights = [0.133 0.213 0.11  0.073 0.081 0.029 0.025 0.184 0.151], Final Value = $2811671.10, Sharpe Ratio = 0.79


Simulation Run = 88
Weights = [0.041 0.215 0.062 0.019 0.276 0.087 0.107 0.151 0.042], Final Value = $3767252.07, Sharpe Ratio = 1.03


Simulation Run = 89
Weights = [0.181 0.043 0.054 0.025 0.264 0.182 0.011 0.053 0.186], Final Value = $4519299.10, Sharpe Ratio = 1.09


Simulation Run = 90
Weights = [0.078 0.162 0.159 0.04  0.187 0.06  0.086 0.136 0.092], Final Value = $3422701.50, Sharpe Ratio = 1.02


Simulation Run = 91
Weights = [0.121 0.035 0.167 0.031 0.011 0.234 0.181 0.083 0.137], Final Value = $4957727.79, Sharpe Ratio = 1.24


Simulation Run = 92
Weights = [0.019 0.19  0.076 0.172 0.093 0.202 0.03  0.004 0.215], Final Value = $4379724.39, Sharpe Ratio = 0.98


Simulation Run = 93
Weights = [0.055 0.146 0.132 0.131 0.039 0.039 0.183 0.127 0.147], Final Value = $3071496.47, Sharpe Ratio = 0.91


Simulation Run = 94
Weights = [0.1   0.035 0.194 0.171 0.197 0.099 0.044 0.034 0.124], Final Value = $3916904.63, Sharpe Ratio = 1.12


Simulation Run = 95
Weights = [0.243 0.014 0.08  0.066 0.323 0.025 0.019 0.197 0.033], Final Value = $3443864.48, Sharpe Ratio = 1.02


Simulation Run = 96
Weights = [0.115 0.006 0.024 0.255 0.129 0.058 0.171 0.174 0.068], Final Value = $3681528.53, Sharpe Ratio = 1.09


Simulation Run = 97
Weights = [0.097 0.024 0.188 0.099 0.12  0.025 0.196 0.118 0.132], Final Value = $3233862.30, Sharpe Ratio = 1.05


Simulation Run = 98
Weights = [0.079 0.104 0.136 0.113 0.194 0.06  0.105 0.202 0.006], Final Value = $3727749.13, Sharpe Ratio = 1.15


Simulation Run = 99
Weights = [0.196 0.182 0.082 0.097 0.075 0.024 0.104 0.111 0.131], Final Value = $2715994.82, Sharpe Ratio = 0.76


Simulation Run = 100
Weights = [0.023 0.177 0.149 0.189 0.039 0.14  0.029 0.109 0.144], Final Value = $3973942.61, Sharpe Ratio = 1.02


Simulation Run = 101
Weights = [0.011 0.214 0.018 0.229 0.028 0.211 0.181 0.06  0.049], Final Value = $4637910.88, Sharpe Ratio = 1.04


Simulation Run = 102
Weights = [0.08  0.064 0.044 0.166 0.181 0.191 0.104 0.132 0.04 ], Final Value = $4890843.94, Sharpe Ratio = 1.26


Simulation Run = 103
Weights = [0.181 0.03  0.232 0.022 0.089 0.07  0.185 0.171 0.02 ], Final Value = $3708483.28, Sharpe Ratio = 1.14


Simulation Run = 104
Weights = [0.067 0.102 0.192 0.117 0.13  0.076 0.076 0.095 0.145], Final Value = $3558839.33, Sharpe Ratio = 1.06


Simulation Run = 105
Weights = [0.096 0.042 0.067 0.017 0.167 0.182 0.185 0.069 0.173], Final Value = $4572688.17, Sharpe Ratio = 1.18


Simulation Run = 106
Weights = [0.07  0.207 0.092 0.2   0.143 0.133 0.112 0.027 0.016], Final Value = $4006331.31, Sharpe Ratio = 1.02


Simulation Run = 107
Weights = [0.076 0.    0.029 0.064 0.202 0.141 0.085 0.316 0.088], Final Value = $4645551.09, Sharpe Ratio = 1.30


Simulation Run = 108
Weights = [0.144 0.031 0.147 0.072 0.152 0.107 0.045 0.142 0.161], Final Value = $3909458.40, Sharpe Ratio = 1.13


Simulation Run = 109
Weights = [0.181 0.066 0.179 0.229 0.067 0.192 0.059 0.014 0.014], Final Value = $4629098.16, Sharpe Ratio = 1.14


Simulation Run = 110
Weights = [0.056 0.011 0.122 0.094 0.054 0.172 0.18  0.181 0.131], Final Value = $4639269.84, Sharpe Ratio = 1.28


Simulation Run = 111
Weights = [0.099 0.025 0.187 0.185 0.01  0.082 0.146 0.102 0.164], Final Value = $3592580.27, Sharpe Ratio = 1.06


Simulation Run = 112
Weights = [0.121 0.202 0.199 0.084 0.104 0.046 0.072 0.066 0.105], Final Value = $3023817.39, Sharpe Ratio = 0.87


Simulation Run = 113
Weights = [0.192 0.059 0.174 0.165 0.017 0.013 0.135 0.182 0.063], Final Value = $2979662.27, Sharpe Ratio = 0.94


Simulation Run = 114
Weights = [0.14  0.044 0.097 0.014 0.115 0.143 0.078 0.18  0.188], Final Value = $4168556.11, Sharpe Ratio = 1.14


Simulation Run = 115
Weights = [0.175 0.039 0.037 0.204 0.172 0.108 0.069 0.176 0.021], Final Value = $4112727.50, Sharpe Ratio = 1.13


Simulation Run = 116
Weights = [0.014 0.209 0.099 0.064 0.07  0.162 0.082 0.196 0.105], Final Value = $4259382.52, Sharpe Ratio = 1.10


Simulation Run = 117
Weights = [0.161 0.151 0.046 0.027 0.146 0.167 0.066 0.075 0.161], Final Value = $4128476.74, Sharpe Ratio = 1.01


Simulation Run = 118
Weights = [0.079 0.005 0.044 0.164 0.161 0.14  0.185 0.15  0.072], Final Value = $4487586.73, Sharpe Ratio = 1.25


Simulation Run = 119
Weights = [0.248 0.085 0.126 0.015 0.156 0.142 0.042 0.027 0.158], Final Value = $3908390.42, Sharpe Ratio = 0.97


Simulation Run = 120
Weights = [0.171 0.055 0.08  0.077 0.016 0.187 0.132 0.132 0.149], Final Value = $4437135.97, Sharpe Ratio = 1.12


Simulation Run = 121
Weights = [0.092 0.159 0.104 0.064 0.019 0.212 0.077 0.161 0.112], Final Value = $4642265.85, Sharpe Ratio = 1.15


Simulation Run = 122
Weights = [0.014 0.158 0.081 0.164 0.128 0.154 0.046 0.1   0.154], Final Value = $4204997.73, Sharpe Ratio = 1.07


Simulation Run = 123
Weights = [0.074 0.162 0.068 0.008 0.181 0.164 0.157 0.045 0.141], Final Value = $4224328.20, Sharpe Ratio = 1.07


Simulation Run = 124
Weights = [0.139 0.134 0.106 0.165 0.11  0.153 0.023 0.102 0.067], Final Value = $4203319.26, Sharpe Ratio = 1.09


Simulation Run = 125
Weights = [0.151 0.024 0.101 0.163 0.1   0.202 0.181 0.037 0.041], Final Value = $4834800.77, Sharpe Ratio = 1.22


Simulation Run = 126
Weights = [0.085 0.169 0.075 0.156 0.136 0.035 0.132 0.125 0.088], Final Value = $3116684.78, Sharpe Ratio = 0.92


Simulation Run = 127
Weights = [0.127 0.127 0.008 0.25  0.091 0.024 0.107 0.122 0.143], Final Value = $2920194.64, Sharpe Ratio = 0.82


Simulation Run = 128
Weights = [0.149 0.209 0.136 0.074 0.193 0.146 0.031 0.028 0.034], Final Value = $4045205.71, Sharpe Ratio = 1.01


Simulation Run = 129
Weights = [0.094 0.135 0.085 0.158 0.136 0.025 0.183 0.111 0.074], Final Value = $3096107.13, Sharpe Ratio = 0.94


Simulation Run = 130
Weights = [0.198 0.167 0.078 0.059 0.01  0.079 0.12  0.199 0.091], Final Value = $3311615.61, Sharpe Ratio = 0.89


Simulation Run = 131
Weights = [0.11  0.062 0.292 0.086 0.007 0.106 0.062 0.114 0.163], Final Value = $3742417.80, Sharpe Ratio = 1.08


Simulation Run = 132
Weights = [0.165 0.037 0.003 0.278 0.233 0.18  0.046 0.05  0.008], Final Value = $4767218.63, Sharpe Ratio = 1.14


Simulation Run = 133
Weights = [0.054 0.121 0.113 0.159 0.126 0.112 0.114 0.066 0.136], Final Value = $3838896.21, Sharpe Ratio = 1.06


Simulation Run = 134
Weights = [0.091 0.192 0.053 0.1   0.18  0.075 0.097 0.187 0.023], Final Value = $3612131.14, Sharpe Ratio = 1.02


Simulation Run = 135
Weights = [0.082 0.056 0.011 0.164 0.168 0.15  0.18  0.082 0.106], Final Value = $4377046.22, Sharpe Ratio = 1.15


Simulation Run = 136
Weights = [0.139 0.015 0.094 0.151 0.15  0.176 0.114 0.135 0.025], Final Value = $4781197.53, Sharpe Ratio = 1.28


Simulation Run = 137
Weights = [0.119 0.109 0.134 0.079 0.166 0.091 0.041 0.103 0.157], Final Value = $3624457.25, Sharpe Ratio = 1.03


Simulation Run = 138
Weights = [0.132 0.101 0.053 0.159 0.095 0.054 0.167 0.158 0.082], Final Value = $3363111.37, Sharpe Ratio = 0.99


Simulation Run = 139
Weights = [0.041 0.189 0.086 0.152 0.193 0.09  0.051 0.015 0.182], Final Value = $3475426.73, Sharpe Ratio = 0.89


Simulation Run = 140
Weights = [0.058 0.021 0.156 0.082 0.224 0.137 0.013 0.3   0.01 ], Final Value = $4731638.49, Sharpe Ratio = 1.35


Simulation Run = 141
Weights = [0.055 0.088 0.157 0.015 0.191 0.113 0.051 0.184 0.146], Final Value = $4049832.09, Sharpe Ratio = 1.18


Simulation Run = 142
Weights = [0.052 0.176 0.133 0.051 0.132 0.18  0.165 0.016 0.094], Final Value = $4391204.60, Sharpe Ratio = 1.11


Simulation Run = 143
Weights = [0.208 0.14  0.093 0.115 0.062 0.125 0.058 0.128 0.071], Final Value = $3805737.04, Sharpe Ratio = 0.99


Simulation Run = 144
Weights = [0.041 0.193 0.043 0.135 0.139 0.053 0.06  0.167 0.17 ], Final Value = $3192275.59, Sharpe Ratio = 0.88


Simulation Run = 145
Weights = [0.069 0.005 0.083 0.121 0.178 0.182 0.028 0.143 0.19 ], Final Value = $4725837.29, Sharpe Ratio = 1.24


Simulation Run = 146

In [125]:
sharpe_ratio_runs

array([1.13630547, 1.09457429, 0.82763611, ..., 1.01056444, 1.30172324,
       1.24575159], shape=(5000,))

In [126]:
sharpe_ratio_runs.argmax()

np.int64(3215)

In [127]:
sharpe_ratio_runs.max()

np.float64(1.4732083336672548)

In [128]:
weights_runs[sharpe_ratio_runs.argmax(), :]

array([0.03149201, 0.00312216, 0.27240665, 0.00670591, 0.12598324,
       0.25541027, 0.07887367, 0.18342851, 0.04257758])

In [130]:
# Return Sharpe ratio, volatility corresponding to the best weights allocation (maximum Sharpe ratio)
optimal_portfolio_return, optimal_volatility, optimal_sharpe_ratio, highest_final_value, optimal_return_on_investment = simulation_engine(weights_runs[sharpe_ratio_runs.argmax(), :], initial_investment)
print('Best Portfolio Metrics Based on {} Monte Carlo Simulation Runs:'.format(sim_runs))
print('  - Portfolio Expected Annual Return = {:.02f}%'.format(optimal_portfolio_return * 100))
print('  - Portfolio Standard Deviation (Volatility) = {:.02f}%'.format(optimal_volatility * 100))
print('  - Sharpe Ratio = {:.02f}'.format(optimal_sharpe_ratio))
print('  - Final Value = INR {:.02f}'.format(highest_final_value))
print('  - Return on Investment = {:.02f}%'.format(optimal_return_on_investment))

Best Portfolio Metrics Based on 5000 Monte Carlo Simulation Runs:
  - Portfolio Expected Annual Return = 30.70%
  - Portfolio Standard Deviation (Volatility) = 16.09%
  - Sharpe Ratio = 1.47
  - Final Value = INR 5673219.08
  - Return on Investment = 467.32%

In [131]:
sim_out_df = pd.DataFrame({'Volatility': volatility_runs.tolist(), 'Portfolio_Return': expected_portfolio_returns_runs.tolist(), 'Sharpe_Ratio': sharpe_ratio_runs.tolist() })
sim_out_df

      Volatility  Portfolio_Return  Sharpe_Ratio
0       0.153242          0.244130      1.136305
1       0.148552          0.232601      1.094574
2       0.151564          0.195440      0.827636
3       0.147334          0.212066      0.964246
4       0.158236          0.254573      1.166439
...          ...               ...           ...
4995    0.146693          0.209018      0.947675
4996    0.158047          0.251310      1.147189
4997    0.151301          0.222900      1.010564
4998    0.158667          0.276541      1.301723
4999    0.165534          0.276214      1.245752

[5000 rows x 3 columns]

In [133]:
# Plot volatility vs. return for all simulation runs
# Highlight the volatility and return that corresponds to the highest Sharpe ratio
import plotly.graph_objects as go
fig = px.scatter(sim_out_df, x = 'Volatility', y = 'Portfolio_Return', color = 'Sharpe_Ratio', size = 'Sharpe_Ratio', hover_data = ['Sharpe_Ratio'] )
fig.update_layout({'plot_bgcolor': "white"})
fig.show()

In [134]:
# Let's highlight the point with the highest Sharpe ratio
fig = px.scatter(sim_out_df, x = 'Volatility', y = 'Portfolio_Return', color = 'Sharpe_Ratio', size = 'Sharpe_Ratio', hover_data = ['Sharpe_Ratio'] )
fig.add_trace(go.Scatter(x = [optimal_volatility], y = [optimal_portfolio_return], mode = 'markers', name = 'Optimal Point', marker = dict(size=[40], color = 'red')))
fig.update_layout(coloraxis_colorbar = dict(y = 0.7, dtick = 5))
fig.update_layout({'plot_bgcolor': "white"})
fig.show()